version: "3.8"
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nice2strangers-frontend-client
    networks:
      - proxy

networks:
  proxy:
    external: true