services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nice2strangers-frontend-client
    expose:
      - "3000" # internal port only
    networks:
      - proxy

networks:
  proxy:
    external: true
