name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy-next:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Next.js repo
        uses: actions/checkout@v3

      - name: Deploy Next.js to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            if [ ! -d "/srv/nice2strangers-frontend-client/.git" ]; then
              git clone https://github.com/jcrocker-cmd/nice2strangers_FE_Client.git
            else
              cd /srv/nice2strangers-frontend-client
              git pull origin main
            fi

            cd /srv/nice2strangers-frontend-client
            docker compose down
            docker compose up -d --build
